import type { Metadata } from 'next';
import { clientCan } from '@sfsr/domain';
import { EmptyState, LockedState, PageHeader } from '@sfsr/ui';
import { requireClient } from '@/lib/session';

export const metadata: Metadata = { title: 'Statement of Account' };

export default async function SoaPage() {
  const session = await requireClient();

  // Deliberately NOT a redirect. RESERVATION.doc reserves the SOA for a
  // Permanent Client; bouncing an Initial Account to another page teaches them
  // nothing about why. Naming the gate is the point of this screen.
  if (!clientCan(session.tier, 'viewOwnSoa')) {
    return (
      <div className="mx-auto max-w-3xl px-6 py-10">
        <PageHeader title="Statement of Account" />
        <LockedState
          title="Available to Permanent Clients"
          description="Your Statement of Account lists your monthly amortisation, applied payments, penalties and discounts, and your outstanding balance."
          requirement="Your Permanent Client Account is issued by our Documentation Department once your reservation is approved and your Contract to Sell has been signed."
        />
      </div>
    );
  }

  return (
    <div className="mx-auto max-w-4xl px-6 py-10">
      <PageHeader
        title="Statement of Account"
        description="Your amortisation schedule and outstanding balance."
      />
      <EmptyState
        title="No statement issued yet"
        description="Statements are generated by the Billing Department once your payment schedule begins. Each one will appear here and can be downloaded as a PDF."
      />
    </div>
  );
}
